all: 
	erl -compile event_manager 
	erl -compile ecalendar 
	erl -compile activiteit 
	erl -compile persoon
	erl -compile debug_log_survivor
	erl -compile auto
	erl -compile auto_manager

	erl -compile testfile

	#start de erlang shell
	erl