all: 
	erl -compile eventManager 
	erl -compile ecalendar 
	erl -compile persoon
	erl -compile auto
	erl -compile autoManager
	erl -compile activiteit

	erl -compile testfile

	#start de erlang shell
	erl
